version: '3.8'

services:
  api:
    build: .
    container_name: banking-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:16
    container_name: banking-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
